server:
  port: 8192
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahmed82/spring-cloud-config-store
          search-paths:
          - '*service'
## All the sub-directory ends with 'service' used for search-paths